Refactor extra training form
WinnerOK/SWP_sport_back pull request #119
Opened 2021-01-09 12:02 UTC by k1rill-fedoseev

2021-01-09 12:23 UTC, WinnerOK commented on adminpage/sport/migrations/0040_auto_20210109_1259.py
> +''')
Добавь, пожалуйста, reverse к этой миграции, чтобы в случае чего можно было откат  сделать

2021-01-09 12:23 UTC, WinnerOK commented on adminpage/sport/models/training.py
> -            models.UniqueConstraint(fields=["group", "start", "end"], name="unique_training"),
Зачем убирать этот constraint?

2021-01-09 12:27 UTC, k1rill-fedoseev commented on adminpage/sport/models/training.py
> -            models.UniqueConstraint(fields=["group", "start", "end"], name="unique_training"),
Он срабатывает когда добавляют > 1 экстра тренировки за день с одинаковыми датами, Евгений жаловался.

2021-01-09 12:32 UTC, WinnerOK commented on adminpage/sport/models/training.py
> -            models.UniqueConstraint(fields=["group", "start", "end"], name="unique_training"),
А same_date constraint у нас уже ранее был удалён?

2021-01-09 12:38 UTC, k1rill-fedoseev commented on adminpage/sport/models/training.py
> -            models.UniqueConstraint(fields=["group", "start", "end"], name="unique_training"),
Я same_date удаляю в 40 миграции, а этот constraint удаляется в 41

2021-01-12 17:10 UTC, WinnerOK requested changes
Создал тренеровку, она создалась, но не отобразилась в календаре в профиле

![image](https://user-images.githubusercontent.com/16958474/104347835-1c72f400-5512-11eb-810c-709c47e90c26.png)

![image](https://user-images.githubusercontent.com/16958474/104347875-27c61f80-5512-11eb-83f5-8d67f41b43b0.png)

![image](https://user-images.githubusercontent.com/16958474/104347956-3f050d00-5512-11eb-9309-db6ff0b5e54d.png)

2021-01-12 17:15 UTC, WinnerOK commented on adminpage/sport/migrations/0040_auto_20210109_1259.py
> +            reverse_sql='ALTER TABLE training ADD CONSTRAINT same_date CHECK (date(start) = date("end"));'
Сейчас потестил. Скорее всего, в бд уже будут строки, который будут нарушать этот констрейт. Либо делаем удаление таких строк (что, мне кажется, нехорошо). Либо все-таки делаем миграцию non-reversible

2021-01-12 17:36 UTC, k1rill-fedoseev commented on adminpage/sport/migrations/0040_auto_20210109_1259.py
> +            reverse_sql='ALTER TABLE training ADD CONSTRAINT same_date CHECK (date(start) = date("end"));'
На проде уж вряд ли придётся эту миграцию ревертить. Поэтому предлагаю оставить так как есть, в любом случае exception будет вылетать при откате.

2021-01-12 17:44 UTC, WinnerOK commented on adminpage/sport/migrations/0040_auto_20210109_1259.py
> +            reverse_sql='ALTER TABLE training ADD CONSTRAINT same_date CHECK (date(start) = date("end"));'
Ну лучше чтобы этот exception соответствовал реальности =)

2021-01-12 19:41 UTC, WinnerOK requested changes

2021-01-12 19:41 UTC, WinnerOK commented on adminpage/api/crud/crud_training.py
> +                       'WHERE t.start > %(start)s AND t."end" < %(end)s '
Если ивент начался на прошлой неделе или закончился на следующей, то он не отобразится в календаре.

Фикс:
```suggestion
                       'WHERE (t.start > %(start)s OR t."end" < %(end)s) '
```

2021-01-12 19:41 UTC, WinnerOK commented on adminpage/api/crud/crud_training.py
> +                       'WHERE t.start > %(start)s AND t."end" < %(end)s '
Как и выше
```suggestion
                       'WHERE (t.start > %(start)s OR t."end" < %(end)s) '
```

2021-01-12 19:42 UTC, WinnerOK commented on adminpage/sport/migrations/0040_auto_20210109_1259.py
> +            reverse_sql='ALTER TABLE training ADD CONSTRAINT same_date CHECK (date(start) = date("end"));'
```suggestion
            reverse_sql=migrations.RunSQL.noop
```

2021-01-13 05:06 UTC, k1rill-fedoseev commented on adminpage/api/crud/crud_training.py
> +                       'WHERE t.start > %(start)s AND t."end" < %(end)s '
Такой фикс не сработает, если ивент идет > 1 недели. Также тут выделятся лишние события.
Я вроде обновил на рабочий вариант.

2021-01-13 15:14 UTC, WinnerOK approved these changes

2021-01-13 15:43 UTC, merged