Remove email from trainers' table for small resolutions
WinnerOK/SWP_sport_back pull request #122
Opened 2021-01-09 19:26 UTC by DmitriyPodpryatov

There's a small bug: 
when rescaling back to large enough width, the email in the "name" column will not change back to name.

2021-01-12 20:00 UTC, WinnerOK requested changes
> when rescaling back to large enough width, the email in the "name" column will not change back to name.

Этот баг все еще остался

2021-01-14 06:47 UTC, k1rill-fedoseev approved these changes

2021-01-14 06:47 UTC, k1rill-fedoseev commented on adminpage/sport/static/sport/js/profile.js
> +    $('.trainer-table-width.show-name-in-trainer-table').attr('class','trainer-table-width hide-name-in-trainer-table');
Есть `$(...).toggleClass(className)` еще для подобных целей.

2021-01-14 09:17 UTC, WinnerOK approved these changes

2021-01-14 09:17 UTC, merged