Add student telegram alias field
WinnerOK/SWP_sport_back pull request #124
Opened 2021-01-10 06:45 UTC by k1rill-fedoseev

2021-01-10 07:20 UTC, WinnerOK requested changes
И импорт алиасов нормально работает, если импортировать только `email, alias` или придётся глянуть и что-то переписать?

2021-01-10 07:20 UTC, WinnerOK commented on adminpage/sport/models/student.py
> +        if type(self.telegram) == str and self.telegram[0] != '@':
Может случиться, что `self.telegram` - не `str` или это всё-таки проверка `is not None `?

2021-01-10 07:20 UTC, WinnerOK commented on adminpage/sport/admin/studentAdmin.py
> +            format_html(f"<a href=\"https://t.me/{obj.telegram[1:]}\">{obj.telegram}</a>")
`format_html` здесь ничего не сделает: питон вставит алиас в строку и все. См в доке как верно юзать формат

[Documentation](https://docs.djangoproject.com/en/3.1/ref/utils/#django.utils.html.format_html )

2021-01-10 07:37 UTC, k1rill-fedoseev commented on adminpage/sport/models/student.py
> +        if type(self.telegram) == str and self.telegram[0] != '@':
Да, это `is not None`, обновил

2021-01-10 07:37 UTC, k1rill-fedoseev commented on adminpage/sport/admin/studentAdmin.py
> +            format_html(f"<a href=\"https://t.me/{obj.telegram[1:]}\">{obj.telegram}</a>")
точно, спасибо

2021-01-10 07:38 UTC, k1rill-fedoseev commented
Починил импорт таблицы со студентами только с двумя колонками `email,telegram`, все отлично работает если все имейлы уже существуют.

2021-01-10 07:39 UTC, WinnerOK commented
> Починил импорт таблицы со студентами только с двумя колонками `email,telegram`, все отлично работает если все имейлы уже существуют.

А если какого-то имейла нет - какое поведение?

2021-01-10 07:40 UTC, WinnerOK submitted a review, later dismissed

2021-01-10 07:42 UTC, k1rill-fedoseev commented
> > Починил импорт таблицы со студентами только с двумя колонками `email,telegram`, все отлично работает если все имейлы уже существуют.
> 
> А если какого-то имейла нет - какое поведение?

Джанга кинет exception типа `null value in column "first_name" violates not-null constraint`

2021-01-10 07:46 UTC, WinnerOK commented
@k1rill-fedoseev Не шибко интуитивно получилось. Надо глянуть можно ли скипать такие записи (не ломая при этом нормальный импорт) потому что мы не сможем узнать какого имейла не существует из входных данных

2021-01-12 20:11 UTC, WinnerOK commented on adminpage/sport/admin/studentAdmin.py
> +            format_html("<a href=\"https://t.me/{}\">{}</a>", obj.telegram[1:], obj.telegram)
Мне кажется, лучше это открывать в новой вкладке, чтобы вкладка с админкой не терялась
```suggestion
            format_html(
                '<a target="_blank" href="https://t.me/{}">{}</a>',
                obj.telegram[1:],
                obj.telegram
            )
```

2021-01-12 20:27 UTC, WinnerOK approved these changes

2021-01-13 05:24 UTC, merged